name: check-xmake-update
run-name: Checking xmake version

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check script
        run: |
          XMAKE_LATEST=$(curl -fs https://api.github.com/repos/xmake-io/xmake/releases/latest | grep -E "\"tag_name\":\s?\"v[0-9.]+\"" | grep -Eo "[0-9.]+")
          if [ "$XMAKE_LATEST" != "3.0.0" ]; then
            echo "::warning:: Xmake has update: $XMAKE_LATEST"
          fi
